// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-BsJwnBkXG1dvW6GLfHy7n6UPyFDzits',
    appId: '1:105627171091:web:dcb0f33f3076a7483042e6',
    messagingSenderId: '105627171091',
    projectId: 'chitieu-92489',
    authDomain: 'chitieu-92489.firebaseapp.com',
    storageBucket: 'chitieu-92489.firebasestorage.app',
    measurementId: 'G-BR4W963ESS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZmHwUiWFi1pMEJM_IrRItJZzaN4Pvqeo',
    appId: '1:105627171091:android:ca56779a6bc2c4623042e6',
    messagingSenderId: '105627171091',
    projectId: 'chitieu-92489',
    storageBucket: 'chitieu-92489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZsbIP3osqotkD5xuGSyJCX9IRaemD_-g',
    appId: '1:105627171091:ios:aab62f39ef0ffffc3042e6',
    messagingSenderId: '105627171091',
    projectId: 'chitieu-92489',
    storageBucket: 'chitieu-92489.firebasestorage.app',
    iosBundleId: 'com.example.quanlichitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZsbIP3osqotkD5xuGSyJCX9IRaemD_-g',
    appId: '1:105627171091:ios:aab62f39ef0ffffc3042e6',
    messagingSenderId: '105627171091',
    projectId: 'chitieu-92489',
    storageBucket: 'chitieu-92489.firebasestorage.app',
    iosBundleId: 'com.example.quanlichitieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-BsJwnBkXG1dvW6GLfHy7n6UPyFDzits',
    appId: '1:105627171091:web:5ef25be5a22142ee3042e6',
    messagingSenderId: '105627171091',
    projectId: 'chitieu-92489',
    authDomain: 'chitieu-92489.firebaseapp.com',
    storageBucket: 'chitieu-92489.firebasestorage.app',
    measurementId: 'G-453RKTMTKD',
  );
}
